# Generated by Django 4.0.8 on 2022-10-25 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('la', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListGroup',
            new_name='List',
        ),
    ]
